version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  julienkeiff:
    image: docker.pkg.github.com/julienkeiff/docker-registry/julienkeiff.fr:latest
    hostname: julienkeiff
    restart: always
    environment:
      PORT: 2007
      mongoDbURL: mongodb://root:gg22r5ASzUbBQuHGSuP9HRPP5ZN6DqK@mongodb/julienkeiff?authSource=admin
    labels:
      com.centurylinklabs.watchtower.enable: "true"

    expose:
      - 2007
    ports:
      - 2007:2007
    links:
      - mongodb
  mongodb:
    image: mongo:4
    hostname: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 2008:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gg22r5ASzUbBQuHGSuP9HRPP5ZN6DqK
    command: mongod --port 27017
    volumes:
      - ./mongo-volume:/data/db