name: Publish to Registry
on:    
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: julienkeiff/docker-registry/julienkeiff.fr
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.pkg.github.com
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"